# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/create_vars',
                'doc_host': 'https://https://github.com/ravennaro/create_vars.git.github.io',
                'git_url': 'https://github.com/https://github.com/ravennaro/create_vars.git/create_vars',
                'lib_path': 'create_vars'},
  'syms': {'create_vars.core': {'create_vars.core.foo': ('core.html#foo', 'create_vars/core.py')}}}
