# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/featime',
                'doc_host': 'https://ravennaro.github.io',
                'git_url': 'https://github.com/ravennaro/featime',
                'lib_path': 'featime'},
  'syms': { 'featime.featime': { 'featime.featime.featime_in_time': ('featime.html#featime_in_time', 'featime/featime.py'),
                                 'featime.featime.mode': ('featime.html#mode', 'featime/featime.py')}}}
